// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["postgres://976441aa6df9ca123e76f492fce80461acf902a8f38bef625ab19da7d362d128:sk_rnEdJNMMeFgZPnzGD32-i@pooled.db.prisma.io:5432/postgres?sslmode=require"],
  },
});
